
version: "3"

# 실행 방법
# docker-compose -f docker-compose.prod.yml up

services:
  backend:
    build:
      context: ./backend

    command: ["python3", "-m", "gunicorn", "myapp.wsgi:app", "--bind", "0.0.0.0:5000"]
    env_file: ./settings/prod.env
    environment:
      FLASK_APP: /myapp
    networks:
      - app-tier
    volumes:
      - ./backend/:/backend/
    depends_on:
      - redis
    ports:
      - 5000:5000
    expose:
      - 5000

  frontend:
    build:
      context: ./frontend
    command: ["yarn", "start"]
    networks:
      - app-tier
    env_file:
      - ./settings/prod.env
    volumes:
      - ./frontend/:/frontend
      - build_folder:/frontend/build
      - ./frontend/node_modules/:/frontend/node_modules
    ports:
      - 3333:3333
    expose: 3333

  colorization-ai:
    build:
      context: ./colorization-AI

    command: ["python3", "-m", "gunicorn","app:app", "--bind", "0.0.0.0:5555"] 
    networks:
      - app-tier
    env_file:
      - ./settings/prod.env
    environment:
      FLASK_APP: ./app.py
    ports:
      - 5555:5555

  nginx:
    build: ./nginx
    ports:
      - 80:8080
    volumes:
      - ./frontend/build:/var/www/frontend
    depends_on:
      - backend
      - frontend
    networks:
      - app-tier

  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    command: rabbitmq-server
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    networks:
      - app-tier
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      - backend
      - colorization-ai

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped  
    env_file:
      - ./settings/prod.env
    depends_on:
      - "rabbit"
      - "backend"
      - "colorization-ai"
    networks:
      - app-tier
    command: ["celery","-A", "myapp.service.PhotoService", "worker", "--loglevel=info"]  
    volumes:
      - ./backend:/usr/src/app

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    ports:
      - 6379:6379
    networks:
      - app-tier
  
networks:
  app-tier:
    driver: bridge

# 컨테이너 내려도 데이터 유지되도록 함
volumes:
  media_volume: null
  build_folder: null