version: "3"

services:


  backend:
    build:
      context: ./backend
      args:
        DJANGO_ALLOWED_HOSTS: "*"
        DJANGO_SECRET_KEY: "*"
        DJANGO_CORS_ORIGIN_WHITELIST: "*"
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - 8000:5000
    volumes:
      - ./backend/:/backend/
    expose:
      - 8000

  frontend:
    build:
      context: ./frontend
    command: [ "yarn", "start" ]
    ports:
      - 80:3000
    volumes:
      - ./frontend/:/frontend
      - ./frontend/node_modules/:/frontend/node_modules
    environment:
      - CI=true
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://localhost:8000
    tty: true

volumes:
  postgres_data_dev: null
